version: '3.4'

services:
  webapi:
    container_name: api_demo
    image: ${DOCKER_REGISTRY-}webapi
    build:
      context: .
      dockerfile: webapi/Dockerfile
    ports: 
          - "8088:8080"      
networks: 
  default:
    name: kong-comic-net